sonar.projectKey=Ashish-6-24_khelsetu-platform
sonar.organization=ashish-6-24
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/test/**,**/tests/**,**/*.test.*,**/*.spec.*,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
