/**
 * Design tokens — JS mirror of CSS custom properties.
 * Use these when you need JS values (inline styles, dynamic logic).
 * Prefer Tailwind classes with var() references in JSX.
 */
export const tokens = {
  color: {
    brand: {
      primary: 'var(--brand-primary)',
      primaryHover: 'var(--brand-primary-hover)',
      primaryActive: 'var(--brand-primary-active)',
      primarySoft: 'var(--brand-primary-soft)',
      primaryInk: 'var(--brand-primary-ink)',
      secondary: 'var(--brand-secondary)',
      secondarySoft: 'var(--brand-secondary-soft)',
      secondaryInk: 'var(--brand-secondary-ink)',
      accent: 'var(--brand-accent)',
      accentHover: 'var(--brand-accent-hover)',
      accentSoft: 'var(--brand-accent-soft)',
      accentInk: 'var(--brand-accent-ink)',
    },
    bg: {
      canvas: 'var(--bg-canvas)',
      surface: 'var(--bg-surface)',
      surfaceRaised: 'var(--bg-surface-raised)',
      surfaceSunken: 'var(--bg-surface-sunken)',
      inverse: 'var(--bg-inverse)',
      glass: 'var(--bg-glass)',
      glassStrong: 'var(--bg-glass-strong)',
    },
    text: {
      primary: 'var(--text-primary)',
      secondary: 'var(--text-secondary)',
      tertiary: 'var(--text-tertiary)',
      muted: 'var(--text-muted)',
      onPrimary: 'var(--text-on-primary)',
      onBrand: 'var(--text-on-brand)',
      onAccent: 'var(--text-on-accent)',
      link: 'var(--text-link)',
    },
    border: {
      subtle: 'var(--border-subtle)',
      default: 'var(--border-default)',
      strong: 'var(--border-strong)',
      brand: 'var(--border-brand)',
    },
    functional: {
      live: 'var(--color-live)',
      liveSoft: 'var(--color-live-soft)',
      success: 'var(--color-success)',
      successSoft: 'var(--color-success-soft)',
      warning: 'var(--color-warning)',
      warningSoft: 'var(--color-warning-soft)',
      danger: 'var(--color-danger)',
      dangerSoft: 'var(--color-danger-soft)',
      info: 'var(--color-info)',
      infoSoft: 'var(--color-info-soft)',
    },
    sport: {
      cricket: 'var(--sport-cricket)',
      football: 'var(--sport-football)',
      volleyball: 'var(--sport-volleyball)',
      basketball: 'var(--sport-basketball)',
    },
  },
  spacing: {
    '0.5': 2,
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    '2xl': 48,
    '3xl': 64,
  },
  typography: {
    display: 40,
    hero: 36,
    heading: 32,
    title: 24,
    subtitle: 18,
    body: 16,
    caption: 13,
    small: 12,
  },
  radius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 999,
  },
  shadow: {
    xs: 'var(--shadow-xs)',
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    brand: 'var(--shadow-brand)',
    gold: 'var(--shadow-gold)',
    glow: 'var(--shadow-glow)',
  },
} as const;
